<?php
namespace App\Controllers;

use App\Core\Controller;
use App\Core\Logger;
use App\Models\ToolModel;
use App\Core\Functions;

class ToolController extends Controller {

    public function crudGeneratorView() {
        $this->requireAdmin(); // Only admins can enter
        $this->loadView('admin/crud-generator');
    }

    public function generateCrud() {
        header('Content-Type: application/json');
        ob_clean();

        // Read form data
        $moduleName = filter_input(INPUT_POST, 'module', FILTER_SANITIZE_STRING);
        $fieldsRaw = filter_input(INPUT_POST, 'fields', FILTER_SANITIZE_STRING);
        $menuLabel = filter_input(INPUT_POST, 'menu_label', FILTER_SANITIZE_STRING);

        $modulesFile = BASE_PATH . '/config/modules.json';
        $modules = file_exists($modulesFile) ? json_decode(file_get_contents($modulesFile), true) : [];

        // Check if it already exists
        $exists = false;
        foreach ($modules as $mod) {
            if (strtolower($mod['slug']) === strtolower($moduleName)) {
                $exists = true;
                echo json_encode(['success' => false, 'message' => "The module '$moduleName' already exists."]);
                return;
            }
        }

        if (!$moduleName /*|| !$fieldsRaw*/) {
            echo json_encode(['success' => false, 'message' => 'All fields are required.']);
            return;
        }

        $slug = strtolower($moduleName);
        $tool = new ToolModel();
        $success = $tool->generateModule($moduleName, $fieldsRaw);

        if ($success) {
            Functions::addModuleToJson($moduleName, $slug, $menuLabel); // ✅ Add to modules.json
            Logger::info("Module '$moduleName' generated by the administrator.");
            echo json_encode(['success' => true, 'message' => "Module '$moduleName' created successfully."]);
        } else {
            echo json_encode(['success' => false, 'message' => "Error creating the module '$moduleName'."]);
        }
    }

    public function deleteModule() {
        header('Content-Type: application/json');
        ob_clean();

        $moduleName = trim($_POST['module'] ?? '');
        if (!$moduleName) {
            echo json_encode(['success' => false, 'message' => 'Module name required.']);
            return;
        }

        $slug = strtolower($moduleName);
        $tool = new ToolModel();
        $success = $tool->deleteModule($moduleName);

        if ($success) {
            Functions::removeModuleFromJson($slug); // ✅ Remove from modules.json
            Logger::info("Module '$moduleName' deleted by the administrator.");
            echo json_encode(['success' => true, 'message' => "Module '$moduleName' deleted successfully."]);
        } else {
            echo json_encode(['success' => false, 'message' => "Error deleting the module '$moduleName'."]);
        }
    }

    public function getModules() {
        header('Content-Type: application/json');
        ob_clean();

        $modulesFile = BASE_PATH . '/config/modules.json';
        if (!file_exists($modulesFile)) {
            echo json_encode([]);
            return;
        }

        $modules = json_decode(file_get_contents($modulesFile), true) ?? [];
        echo json_encode($modules);
    }


}
